spring:
  application:
    name: eureka-client
  # 配置数据源 mysql, 需指定 driver
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  # 显示查询数据库的 sql
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: clientConfigName

# 访问 controller 的端口和上下文
server:
  port: 9999
  servlet:
    context-path: /demo



