server:
  port: 7001
  servlet:
    # controller 的请求上下文
    context-path: /ad-search

# 注册中心的 应用名称
spring:
  application:
    name: eureka-client-ad-search
  # java 持久化的配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    # 格式化sql
    properties:
      hibernate.format_sql: true
    # 取消懒加载
    open-in-view: false
  # 数据源
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/db_user
    username: root
    password: 123456
    # 最大和最小的 连接数
    tomcat:
      max-active: 4
      min-idle: 2

#  注册到  服务中心到
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

# 访问其他微服务
feign:
  hystrix:
    enabled: true

# 获取所有暴露的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

